# Generated by Django 5.0.8 on 2025-01-09 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='email',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='sent_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='email',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='email',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='email',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='recipients',
            field=models.CharField(default='some@gmail.com', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
