# Generated by Django 5.0.7 on 2024-07-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Enter the name of the user role.', max_length=100)),
                ('description', models.TextField(help_text='Provide a description for the user role.')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the first name of the user.', max_length=100)),
                ('last_name', models.CharField(help_text='Enter the last name of the user.', max_length=100)),
                ('email', models.EmailField(help_text='Enter the email of the user.', max_length=254)),
                ('password', models.CharField(help_text='Enter the password of the user.', max_length=100)),
                ('image', models.ImageField(help_text='Upload an image for the user.', upload_to='users/')),
                ('phone', models.CharField(help_text='Enter the phone number of the user.', max_length=20)),
                ('address', models.TextField(help_text='Enter the address of the user.')),
                ('city', models.CharField(help_text='Enter the city of the user.', max_length=100)),
                ('country', models.CharField(help_text='Enter the country of the user.', max_length=100)),
                ('postal_code', models.CharField(help_text='Enter the postal code of the user.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(help_text='Select the role for the user.', on_delete=django.db.models.deletion.CASCADE, to='users.userrole')),
            ],
        ),
    ]
