# Generated by Django 5.0.8 on 2025-01-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_mail',
            field=models.EmailField(blank=True, help_text="The user's company email address.", max_length=254, null=True, unique=True),
        ),
    ]
