# Generated by Django 5.0.6 on 2024-06-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='An image representing the category', null=True, upload_to='design_categories/'),
        ),
    ]
