# Generated by Django 5.0.7 on 2024-08-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement for the product. Eg. kg, m, cm, etc.', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.zone')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'zone')},
            },
        ),
    ]
