# Generated by Django 5.0.7 on 2024-07-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productzone',
            name='unit',
            field=models.CharField(default=1, help_text='Unit of measurement for the product. Eg. kg, m, cm, etc.', max_length=10),
            preserve_default=False,
        ),
    ]
