# Generated by Django 5.0.7 on 2024-07-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_productzone_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productzone',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measurement for the product. Eg. kg, m, cm, etc.', max_length=10),
        ),
    ]
