version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  static:
