# Generated by Django 5.0.8 on 2024-10-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(blank=True, help_text='Enter a short description of the category', max_length=255, null=True),
        ),
    ]
