# Generated by Django 5.0.8 on 2024-10-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the post', null=True, upload_to='blog/posts/'),
        ),
    ]
