# Generated by Django 5.0.6 on 2024-06-15 16:20

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the features.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the plant category.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Provide a description for the plant category.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the plant category.', null=True, upload_to='plant_categories/')),
            ],
            options={
                'verbose_name': 'Plant Category',
                'verbose_name_plural': 'Plant Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the planter category.', max_length=100)),
                ('description', models.TextField(help_text='Provide a description for the planter category.')),
                ('image', models.ImageField(help_text='Upload an image for the planter category.', upload_to='planter_categories/')),
            ],
            options={
                'verbose_name': 'Planter Category',
                'verbose_name_plural': 'Planter Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the service category.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Provide a description for the service category.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the service category.', null=True, upload_to='service_categories/')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, help_text='Enter the serial number for the service type.', null=True)),
                ('title', models.CharField(help_text='Enter the title of the service type.', max_length=100)),
                ('description', models.TextField(help_text='Provide a description for the service type.')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the service type.', null=True, upload_to='service_types/')),
                ('budget_range', models.CharField(blank=True, help_text='Enter the budget range for the service type.', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Service Plan',
                'verbose_name_plural': 'Service Plans',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the idea.', max_length=100)),
                ('description', models.TextField(help_text='Provide a description for the idea.')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the idea.', null=True, upload_to='ideas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the name of the plant.', max_length=100)),
                ('indoor_or_outdoor', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], help_text='Select whether the plant is meant for indoor or outdoor use.', max_length=10)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], help_text='Select the size of the plant.', max_length=20)),
                ('description', models.TextField(help_text='Provide a description for the plant.')),
                ('care_instructions', models.TextField(help_text='Provide care instructions for the plant.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(blank=True, help_text='Select the features that describe the plant.', to='main.features')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('category', models.ForeignKey(help_text='Select the category for the plant.', on_delete=django.db.models.deletion.CASCADE, to='main.plantcategory')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Planter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Enter the model of the planter.', max_length=100)),
                ('size', models.CharField(help_text='Enter the size of the planter.', max_length=20)),
                ('description', models.TextField(help_text='Provide a description for the planter.')),
                ('color', models.CharField(help_text='Enter the color of the planter.', max_length=50)),
                ('is_custom', models.BooleanField(default=False, help_text='Check if the planter is custom-made.')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('category', models.ForeignKey(help_text='Select the category for the planter.', on_delete=django.db.models.deletion.CASCADE, to='main.plantercategory')),
            ],
            options={
                'verbose_name': 'Planter',
                'verbose_name_plural': 'Planters',
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='PlanterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image for the planter.', upload_to='planter_images/')),
                ('short_description', models.CharField(help_text='Enter a short description for the planter image.', max_length=255)),
                ('planter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.planter')),
            ],
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image for the plant.', upload_to='plant_images/')),
                ('short_description', models.CharField(help_text='Enter a short description for the plant image.', max_length=255)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the service.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Provide a description for the service.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the service.', null=True, upload_to='services/')),
                ('budget_range', models.CharField(blank=True, help_text='Enter the budget range for the service.', max_length=50, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('category', models.ForeignKey(help_text='Select the category for the service.', on_delete=django.db.models.deletion.CASCADE, to='main.servicecategory')),
                ('type', models.ForeignKey(help_text='Select the type for the service.', on_delete=django.db.models.deletion.CASCADE, to='main.servicetype')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTypeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, help_text='Enter the serial number for the feature.', null=True)),
                ('title', models.CharField(help_text='Enter the title of the feature.', max_length=100)),
                ('service_type', models.ForeignKey(help_text='Select the service type for the feature.', on_delete=django.db.models.deletion.CASCADE, related_name='service_type_features', to='main.servicetype')),
            ],
            options={
                'verbose_name': 'Service Type Feature',
                'verbose_name_plural': 'Service Type Features',
                'ordering': ['serial'],
            },
        ),
    ]
