# Generated by Django 5.0.6 on 2024-07-21 17:38

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='care_instructions',
            field=models.TextField(blank=True, help_text='Provide care instructions for the plant.', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a description for the plant.', null=True),
        ),
        migrations.AlterField(
            model_name='planter',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a description for the planter.', null=True),
        ),
        migrations.AlterField(
            model_name='planter',
            name='size',
            field=models.CharField(blank=True, help_text='Enter the size of the planter.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plantercategory',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a description for the planter category.', null=True),
        ),
        migrations.AlterField(
            model_name='plantercategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the planter category.', null=True, upload_to='planter_categories/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(blank=True, help_text='Enter the content of the testimonial.', null=True),
        ),
    ]
