# Generated by Django 5.0.7 on 2024-07-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='plant',
            name='availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=55.55, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
