# Generated by Django 5.0.6 on 2024-06-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterModelOptions(
            name='plantcategory',
            options={'ordering': ['name'], 'verbose_name': 'Plant Category', 'verbose_name_plural': 'Plant Categories'},
        ),
        migrations.AlterModelOptions(
            name='planter',
            options={'ordering': ['model'], 'verbose_name': 'Planter', 'verbose_name_plural': 'Planters'},
        ),
        migrations.AlterModelOptions(
            name='plantercategory',
            options={'ordering': ['name'], 'verbose_name': 'Planter Category', 'verbose_name_plural': 'Planter Categories'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['title'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['title'], 'verbose_name': 'Service Type', 'verbose_name_plural': 'Service Types'},
        ),
    ]
