# Generated by Django 5.0.6 on 2024-05-27 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='An image related to the review.', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(help_text='The review the image belongs to.', on_delete=django.db.models.deletion.CASCADE, to='main.review')),
            ],
            options={
                'verbose_name': 'Review Image',
                'verbose_name_plural': 'Review Images',
            },
        ),
    ]
