# Generated by Django 5.0.7 on 2024-08-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['id'], 'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
    ]
