# Generated by Django 5.0.7 on 2024-08-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('tags', '0001_initial'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='plants', to='main.feature'),
        ),
        migrations.AddField(
            model_name='plant',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='plants', to='main.image'),
        ),
        migrations.AddField(
            model_name='plant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='plants', to='tags.taggeditem'),
        ),
        migrations.AddField(
            model_name='plant',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='plants', to='zone.productzone'),
        ),
    ]
