# Generated by Django 5.0.7 on 2024-08-03 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feature',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='plantcategory',
            name='featured_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.plantcategory'),
        ),
        migrations.AddField(
            model_name='plantercategory',
            name='featured_planter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.planter'),
        ),
        migrations.AddField(
            model_name='planter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plantercategory'),
        ),
        migrations.AddField(
            model_name='plantingaccessories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plantingaccessoriescategory'),
        ),
        migrations.AddField(
            model_name='plantingaccessories',
            name='promotion',
            field=models.ManyToManyField(blank=True, to='main.promotion'),
        ),
        migrations.AddField(
            model_name='planter',
            name='promotion',
            field=models.ManyToManyField(blank=True, to='main.promotion'),
        ),
        migrations.AddField(
            model_name='plant',
            name='promotion',
            field=models.ManyToManyField(blank=True, to='main.promotion'),
        ),
        migrations.AlterUniqueTogether(
            name='servicecategory',
            unique_together={('title', 'type')},
        ),
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.servicecategory'),
        ),
        migrations.AddField(
            model_name='projects',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.servicecategory'),
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamcontact',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
