# Generated by Django 5.0.7 on 2024-07-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_title_plant_name_plant_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
