# Generated by Django 5.0.7 on 2024-08-31 17:59

import main.models
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_feature_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=main.models.upload_to, validators=[main.validators.validate_file_size]),
        ),
    ]
