# Generated by Django 5.0.6 on 2024-07-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ideas_tags_alter_plant_care_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planter',
            name='color',
            field=models.CharField(blank=True, help_text='Enter the color of the planter.', max_length=50, null=True),
        ),
    ]
