# Generated by Django 5.0.6 on 2024-05-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, help_text='A unique slug for the category.', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.SlugField(default=1, help_text='A unique slug for the plant.', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
