# Generated by Django 5.0.7 on 2024-08-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_plant_features_plant_images_plant_tags_plant_zones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='features',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='images',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='zones',
        ),
    ]
