# Generated by Django 5.0.7 on 2024-07-26 15:02

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customer_birth_date_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/', validators=[main.validators.validate_file_size]),
        ),
    ]
