# Generated by Django 5.0.6 on 2024-05-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_slug_plant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(help_text='An image of the plant.', upload_to='plant/'),
        ),
    ]
