# Generated by Django 5.0.6 on 2024-06-20 18:17

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_planterfeatures_planter_features'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planter',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Add tags that describe the planter.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
