# Generated by Django 5.0.7 on 2024-08-09 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcontact',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
