# Generated by Django 5.0.6 on 2024-06-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_plant_price_alter_planter_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(blank=True, choices=[('flowering', 'Flowering'), ('non-flowering', 'Non-flowering'), ('succulent', 'Succulent'), ('tropical', 'Tropical'), ('herb', 'Herb'), ('fruit', 'Fruit')], default='flowering', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
