# Generated by Django 5.0.7 on 2024-07-24 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_plant_availability_alter_plant_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.RemoveField(
            model_name='plant',
            name='indoor_or_outdoor',
        ),
        migrations.AddField(
            model_name='plant',
            name='location_type',
            field=models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Both', 'Both')], default='Both', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.SmallIntegerField(help_text='Price in BDT', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='promotion',
            field=models.ManyToManyField(blank=True, to='main.promotion'),
        ),
    ]
