# Generated by Django 5.0.6 on 2024-06-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_planter_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='short_description',
            field=models.CharField(blank=True, help_text='Enter a short description for the plant.', max_length=255, null=True),
        ),
    ]
