# Generated by Django 5.0.6 on 2024-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_plantcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planter',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Check if the planter is custom-made.'),
        ),
    ]
