# Generated by Django 5.0.7 on 2024-08-09 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_teamcontact_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcontact',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.team'),
        ),
    ]
