# Generated by Django 5.0.7 on 2024-08-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_upcoming',
            field=models.BooleanField(default=True),
        ),
    ]
