# Generated by Django 5.0.7 on 2024-09-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_is_upcoming'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideas',
            options={'ordering': ['-created_at'], 'verbose_name': 'Idea', 'verbose_name_plural': 'Ideas'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-year'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
