# Generated by Django 5.0.7 on 2024-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_teamcontact_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
