# Generated by Django 5.0.6 on 2024-06-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_plant_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='short_description',
        ),
        migrations.AddField(
            model_name='planter',
            name='short_description',
            field=models.CharField(blank=True, help_text='Enter a short description for the plant.', max_length=255, null=True),
        ),
    ]
