# Generated by Django 5.0.7 on 2024-07-25 00:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_promotion_created_at_promotion_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='availability',
        ),
        migrations.AddField(
            model_name='plant',
            name='inventory',
            field=models.PositiveIntegerField(default=1, help_text='Number of plants in stock', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.plantcategory'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.FloatField(blank=True, help_text='Discount in percentage, if any', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
