# Generated by Django 5.0.6 on 2024-06-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_plant_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planterimage',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='plantimage',
            name='short_description',
        ),
    ]
