# Generated by Django 5.0.7 on 2024-07-25 04:03

import django.core.validators
import django.utils.timezone
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_price_plant_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planter',
            name='inventory',
            field=models.PositiveIntegerField(default=1, help_text='Number of plants in stock', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='planter',
            name='promotion',
            field=models.ManyToManyField(blank=True, to='main.promotion'),
        ),
        migrations.AddField(
            model_name='planter',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='planter',
            name='unit_price',
            field=models.SmallIntegerField(default=200, help_text='Price in BDT', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ideas/', validators=[main.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='plantcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_categories/', validators=[main.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='planter',
            name='size',
            field=models.CharField(blank=True, help_text='Size in inches', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plantercategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='planter_categories/', validators=[main.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='planterimage',
            name='image',
            field=models.ImageField(upload_to='planter_images/', validators=[main.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(upload_to='plant_images/', validators=[main.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_images/', validators=[main.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_categories/', validators=[main.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='service_images/', validators=[main.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_members/', validators=[main.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[main.validators.validate_file_size]),
        ),
    ]
