# Generated by Django 5.0.6 on 2024-06-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_servicetypefeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='budget_range',
            field=models.CharField(blank=True, help_text='Enter the budget range for the service type.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the service type.', null=True, upload_to='service_types/'),
        ),
    ]
