# Generated by Django 5.0.7 on 2024-07-25 08:41

import django.core.validators
import django.db.models.deletion
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_planter_created_at_planter_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantingAccessoriesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='planting_accessories_categories/', validators=[main.validators.validate_file_size])),
            ],
            options={
                'verbose_name': 'Planting Accessory Category',
                'verbose_name_plural': 'Planting Accessory Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='plant',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='planter',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='PlantingAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('inventory', models.PositiveIntegerField(default=1, help_text='Number of items in stock', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion', models.ManyToManyField(blank=True, to='main.promotion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plantingaccessoriescategory')),
            ],
            options={
                'verbose_name': 'Planting Accessory',
                'verbose_name_plural': 'Planting Accessories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantingAccessoriesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='planting_accessories_images/', validators=[main.validators.validate_file_size])),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('planting_accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plantingaccessories')),
            ],
            options={
                'verbose_name': 'Planting Accessory Image',
                'verbose_name_plural': 'Planting Accessory Images',
            },
        ),
    ]
