# Generated by Django 5.0.7 on 2024-08-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcontact',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
