# Generated by Django 5.0.6 on 2024-06-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_planterimage_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planterimage',
            name='short_description',
            field=models.CharField(blank=True, help_text='Enter a short description for the image.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='short_description',
            field=models.CharField(blank=True, help_text='Enter a short description for the image.', max_length=255, null=True),
        ),
    ]
