# Generated by Django 5.0.6 on 2024-06-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_servicetype_budget_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetypefeature',
            name='service_type',
            field=models.ForeignKey(help_text='Select the service type for the feature.', on_delete=django.db.models.deletion.CASCADE, related_name='service_type_features', to='main.servicetype'),
        ),
    ]
