# Generated by Django 5.0.6 on 2024-06-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_planterimage_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, choices=[('Commercial', 'Commercial'), ('Residential', 'Residential')], default='Residential', help_text='Select the type of service.', max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='servicetypefeature',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='ServiceTypeFeature',
        ),
    ]
