# Generated by Django 5.0.6 on 2024-06-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_servicetypefeature_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='budget_range',
            field=models.CharField(blank=True, help_text='Enter the budget range for the service.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a description for the service.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the service.', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a description for the service category.', null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the service category.', null=True, upload_to='service_categories/'),
        ),
    ]
