# Generated by Django 5.0.6 on 2024-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_service_budget_range_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetypefeature',
            options={'ordering': ['serial'], 'verbose_name': 'Service Type Feature', 'verbose_name_plural': 'Service Type Features'},
        ),
        migrations.AddField(
            model_name='servicetypefeature',
            name='serial',
            field=models.IntegerField(blank=True, help_text='Enter the serial number for the feature.', null=True),
        ),
    ]
