# Generated by Django 5.0.6 on 2024-06-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_service_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['id'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='no',
            field=models.PositiveIntegerField(default=1, help_text='Enter the number of the service category.'),
            preserve_default=False,
        ),
    ]
