# Generated by Django 5.0.6 on 2024-06-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_servicecategory_options_servicecategory_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['no'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='no',
            field=models.PositiveIntegerField(help_text='Enter the number of the service category.', unique=True),
        ),
    ]
