# Generated by Django 5.0.6 on 2024-06-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_service_type_servicecategory_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicecategory',
            unique_together={('title', 'type')},
        ),
    ]
