# Generated by Django 5.0.6 on 2024-07-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_servicecategory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the team member.', max_length=100)),
                ('position', models.CharField(help_text='Enter the position of the team member.', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the team member.', null=True, upload_to='team_members/')),
                ('phone_number', models.CharField(blank=True, help_text='Enter the phone number of the team member.', max_length=15, null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Enter the Facebook URL of the team member.', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Enter the Twitter URL of the team member.', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='Enter the LinkedIn URL of the team member.', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Enter the Instagram URL of the team member.', null=True)),
                ('bio', models.TextField(help_text='Enter the bio of the team member.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the testimonial author.', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the testimonial author.', null=True, upload_to='testimonials/')),
                ('content', models.TextField(help_text='Enter the content of the testimonial.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
