# Generated by Django 5.0.6 on 2024-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_team_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bio',
            field=models.TextField(blank=True, help_text='Enter the bio of the team member.', null=True),
        ),
    ]
