# Generated by Django 5.0.6 on 2024-07-10 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_team_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.CharField(blank=True, help_text='Enter the name of the client.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the year when the service was provided.', null=True),
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image for the service.', upload_to='service_images/')),
                ('short_description', models.CharField(blank=True, help_text='Enter a short description for the image.', max_length=255, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Select the categories that describe the service.', to='main.servicecategory'),
        ),
    ]
