# Generated by Django 5.0.6 on 2024-07-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_service_image_service_client_service_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Select the categories that describe the service.', related_name='services', to='main.servicecategory'),
        ),
    ]
