# Generated by Django 5.0.6 on 2024-07-12 12:32

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_category_service_categories'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='service',
            name='client',
        ),
        migrations.RemoveField(
            model_name='service',
            name='year',
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the project.', max_length=100)),
                ('categories', models.CharField(blank=True, help_text='Enter the categories for the project.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Provide a description for the project.', null=True)),
                ('client', models.CharField(blank=True, help_text='Enter the name of the client.', max_length=100, null=True)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Enter the year when the project was completed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image for the project.', upload_to='project_images/')),
                ('short_description', models.CharField(blank=True, help_text='Enter a short description for the image.', max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projects')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
    ]
