# Generated by Django 5.0.6 on 2024-07-12 13:10

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_service_budget_range_remove_service_client_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Add tags that describe the project.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
