# Generated by Django 5.0.6 on 2024-06-01 08:33

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category.', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='A unique slug for the category.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the category.', null=True)),
                ('image', models.ImageField(help_text='An image representing the category.', upload_to='plant_category/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The common name of the plant.', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='A unique slug for the plant.', max_length=255, unique=True)),
                ('scientific_name', models.CharField(blank=True, help_text='The scientific name of the plant.', max_length=255, null=True)),
                ('toxicity', models.CharField(help_text="Information about the plant's toxicity to pets and humans.", max_length=255)),
                ('is_pate_safe', models.BooleanField(default=True, help_text='Whether the plant is safe for pets.')),
                ('is_air_purifying', models.BooleanField(default=False, help_text='Whether the plant is an air purifier.')),
                ('description', models.TextField(blank=True, help_text='A brief description of the plant.', null=True)),
                ('care_instructions', models.TextField(blank=True, help_text='Instructions on how to care for the plant.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('category', models.ForeignKey(help_text='The category to which the plant belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='plant_category', to='plant.plantcategory')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'unique_together': {('name', 'scientific_name')},
            },
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='An image of the plant.', upload_to='plant/')),
                ('alt_text', models.CharField(blank=True, help_text='A brief description of the image.', max_length=255, null=True)),
                ('source', models.CharField(blank=True, help_text='The source of the image.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(help_text='The plant the image belongs to.', on_delete=django.db.models.deletion.CASCADE, to='plant.plant')),
            ],
            options={
                'verbose_name': 'Plant Image',
                'verbose_name_plural': 'Plant Images',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='The rating given to the plant (1-5).')),
                ('comment', models.TextField(help_text='The content of the review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(help_text='The plant being reviewed.', on_delete=django.db.models.deletion.CASCADE, to='plant.plant')),
                ('user', models.ForeignKey(help_text='The user who wrote the review.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='An image related to the review.', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(help_text='The review the image belongs to.', on_delete=django.db.models.deletion.CASCADE, to='plant.review')),
            ],
            options={
                'verbose_name': 'Review Image',
                'verbose_name_plural': 'Review Images',
            },
        ),
    ]
