# Generated by Django 5.0.6 on 2024-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price of the plant.', max_digits=10, null=True),
        ),
    ]
