# Generated by Django 5.0.6 on 2024-06-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_plant_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='is_pate_safe',
            new_name='is_pet_safe',
        ),
    ]
