# Generated by Django 5.0.7 on 2024-07-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ourclients',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ourclients',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='screen_size',
            field=models.CharField(choices=[('Small Screen', 'Small Screen'), ('Large Screen', 'Large Screen')], max_length=20),
        ),
    ]
