# Generated by Django 5.0.7 on 2024-08-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='alt_text',
            field=models.CharField(default='Banner Image', max_length=255),
        ),
    ]
