# Generated by Django 5.0.6 on 2024-07-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='screen_size',
            field=models.CharField(choices=[('Small Screen', 'Large Screen'), ('Large Screen', 'Large Screen')], default=1, help_text='Select the size of the plant.', max_length=20),
            preserve_default=False,
        ),
    ]
